name: test

on:
  schedule:
    - cron: '45 18 * * 1'  # Triggers Job1: Every Monday at 12:15 AM IST (6:45 PM UTC)
    - cron: '50 2 * * 2'  # Triggers Job2: Every Tuesday at 8:20 AM IST (2:50 AM UTC)
    - cron: '0 11 * * 3'  # Triggers Job3: Every Wednesday at 4:30 PM IST (11:00 AM UTC)
    - cron: '45 18 * * 4'  # Triggers Job4: Every Thursday at 12:15 AM IST (6:45 PM UTC previous day)
    - cron: '50 2 * * 5'  # Triggers Job5: Every Friday at 8:20 AM IST (2:50 AM UTC)
    - cron: '0 11 * * 6'  # Triggers Job6: Every Saturday at 4:30 PM IST (11:00 AM UTC)
    - cron: '50 2 * * 0'  # Triggers Job7: Every Sunday at 8:20 AM IST (2:50 AM UTC)
  workflow_dispatch:
permissions: 
  contents: read
  actions: write

jobs: 
  build: 
    runs-on: ubuntu-latest
    timeout-minutes: 280

    steps:
    - uses: actions/checkout@v3

    - name: Debug Time
      run: date

    - name: app
      run: |
        chmod +x entrypoint.sh

    - name: app run
      run: |
        bash entrypoint.sh
